// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBISTag3yFE5cpDg0kVbsmONSAhPkK5z_A',
    appId: '1:1013088948833:web:98614433cb9e5150461020',
    messagingSenderId: '1013088948833',
    projectId: 'spellwork-a66fe',
    authDomain: 'spellwork-a66fe.firebaseapp.com',
    databaseURL: 'https://spellwork-a66fe-default-rtdb.firebaseio.com',
    storageBucket: 'spellwork-a66fe.appspot.com',
    measurementId: 'G-RJPY1S02NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlcdHc6cSvkZeicar7hgS05PC063wQPU8',
    appId: '1:1013088948833:android:edd69486c38feb50461020',
    messagingSenderId: '1013088948833',
    projectId: 'spellwork-a66fe',
    databaseURL: 'https://spellwork-a66fe-default-rtdb.firebaseio.com',
    storageBucket: 'spellwork-a66fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKf-5n_RpnTuJybkvZXvXD8GlaUlLzmBI',
    appId: '1:1013088948833:ios:476da02682d462ec461020',
    messagingSenderId: '1013088948833',
    projectId: 'spellwork-a66fe',
    databaseURL: 'https://spellwork-a66fe-default-rtdb.firebaseio.com',
    storageBucket: 'spellwork-a66fe.appspot.com',
    iosClientId: '1013088948833-r9emsjt17f2tqdqds9br37fn58h305jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.spellworkCert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKf-5n_RpnTuJybkvZXvXD8GlaUlLzmBI',
    appId: '1:1013088948833:ios:476da02682d462ec461020',
    messagingSenderId: '1013088948833',
    projectId: 'spellwork-a66fe',
    databaseURL: 'https://spellwork-a66fe-default-rtdb.firebaseio.com',
    storageBucket: 'spellwork-a66fe.appspot.com',
    iosClientId: '1013088948833-r9emsjt17f2tqdqds9br37fn58h305jf.apps.googleusercontent.com',
    iosBundleId: 'com.example.spellworkCert',
  );
}
